/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

let fibInc = 3; // First two terms have been added
const fibMax = 4e+6; // 4000000
const arrFib = [1, 2]; // Add first two terms
let result = 2; // initial sum of Even-valued terms

while (result <= fibMax) {
    const sum = arrFib[arrFib.length - 1] + arrFib[arrFib.length - 2];
    if (sum % 2 === 0) {
        result += sum;
    }
    arrFib.push(sum);
    fibInc++
    continue;
}

console.log(result) // 4613732
